[package]
name = "learn-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]

winit = "0.26.1"
wgpu = "0.13.1"

# tool
image = "0.24.3"
bytemuck = { version = "1.10.0", features = ["derive"] }
nalgebra = { version = "0.31.0", features = ["bytemuck"] }

# async
tokio = { version = "1.20.0", default-features = false, features = ["macros","signal","rt-multi-thread"] }

# logging
env_logger = "0.9.0"
log = "0.4"

# build
cfg-if = "1.0.0"

# error handling
thiserror = "1.0.31"
color-eyre = "0.6.2"
tracing-error = "0.2.0"
color-spantrace = "0.2.0"

[profile.release]
opt-level = 'z'
debug = 1
lto = true
incremental = false
codegen-units = 1
strip = "debuginfo"
